// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.34;

import {Test} from "forge-std/Test.sol";
import {WadMath} from "../../src/libraries/WadMath.sol";

// Morrow Finance — Solidity vs Python differential test for WadMath.
// @author adiii.eth

/// @notice Solidity vs Python differential test. Vectors generated by sim/vectors/generate.py, 2000 random
/// cases, columnar JSON format (one array per field, read with parseJsonUintArray).
contract WadMathDiffTest is Test {
    function test_diff_wadmath() public {
        string memory json = vm.readFile("sim/vectors/wadmath.json");
        uint256[] memory xs = vm.parseJsonUintArray(json, ".x");
        uint256[] memory ys = vm.parseJsonUintArray(json, ".y");
        uint256[] memory ds = vm.parseJsonUintArray(json, ".d");
        uint256[] memory downs = vm.parseJsonUintArray(json, ".down");
        uint256[] memory ups = vm.parseJsonUintArray(json, ".up");

        assertGt(xs.length, 0, "vector file must not be empty");
        assertEq(xs.length, ys.length);
        assertEq(xs.length, ds.length);
        assertEq(xs.length, downs.length);
        assertEq(xs.length, ups.length);

        for (uint256 i = 0; i < xs.length; i++) {
            assertEq(WadMath.mulDivDown(xs[i], ys[i], ds[i]), downs[i], "mulDivDown mismatch vs python twin");
            assertEq(WadMath.mulDivUp(xs[i], ys[i], ds[i]), ups[i], "mulDivUp mismatch vs python twin");
        }
    }
}
